# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  focal_gcc9_conda_asan:
    docker:
    - image: circleci/buildpack-deps:focal
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_focal_gcc9_conda_asan.sh
  focal_gcc9_conda_coverage:
    docker:
    - image: circleci/buildpack-deps:focal
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_focal_gcc9_conda_coverage.sh
  focal_gcc9_llvm10_conda_asan:
    docker:
    - image: circleci/buildpack-deps:focal
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_focal_gcc9_llvm10_conda_asan.sh
  focal_gcc9_llvm11_conda_asan:
    docker:
    - image: circleci/buildpack-deps:focal
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_focal_gcc9_llvm11_conda_asan.sh

workflows:
  version: 2.1
  all_builds:
    jobs:
    - focal_gcc9_conda_asan
    - focal_gcc9_conda_coverage
    - focal_gcc9_llvm10_conda_asan
    - focal_gcc9_llvm11_conda_asan
